### PR TITLE
Add SPI chain, individual SPI pins

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
Here's my ideas on how to implement SPI daisy chaining in the library.

I've added variables and commands to set them for these purposes.

I have not been able to test this.    I expect new hardware to arrive in 3-4 days 
so I'll be able to have enough confidence in it to make a request to merge it.

---

To do chaining use the command 
**`void L6470::set_chain_info(const byte axis, const byte chain_position)`**

This adds entries to an array that holds information on what order the data for each axis is sent,  

If there is data in this array then the chain XFER routine will be used.

Not a very efficient use of bandwidth as each transmission consists of one byte per driver but only one byte has any value,

---

I've added variables so that each driver can have its own SPI.  I've added a soft SPI that can use those pins.

---

I've added the capability to automatically use an external XFER routine. I did this by creating weak functions and then only using them if the internal soft SPI isn't used.  To use an external SPI just:

1. Don't init the soft SPI pins
2.  Write corresponding routines with the same names & arguments

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
I think I'm done with the L6470.

I'm also playing with a powerSTEP01 driver.  It's a higher power version of the L6470 but there are enough differences that it'll be several more days before I have it fully functional..  There's changes in register bit definitions and register addresses and possibly setup/init settings.

I've backed out the powerSTEP01 changes from the library.

Maybe it's better to have a separate library for the powrSTEP01.

**Comment by thinkyhead** [comment]
A separate library for powrSTEP01 might be the best idea. If it's close enough to the standard L6470 then they'd end up merging, but in the meantime it may be easier to work on it in isolation.

**Comment by thinkyhead** [comment]
Changes supporting MarlinFirmware/Marlin#12895 and under testing there.

**Comment by thinkyhead** [comment]
Merged to `dev` — and updated the Marlin `platformio.ini` to pull from `dev`. I'll push to `master` in a couple days, after `dev` has had a chance to be tested a bit more.

**Pull request merged**
